language: android
jdk: oraclejdk8

android:
  components:
    - android-23
    - build-tools-23.0.1
    - extra-android-m2repository
    - extra-android-support

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
